services:
  oro_behat_extension.health_checker.fixtures_checker:
    class: Labudzinski\TestFrameworkBundle\Behat\HealthChecker\FixturesChecker
    arguments:
      - '@oro_test.context.fixture_loader'
      - '@oro_behat_extension.fixtures.yml_parser'
      - '@oro_behat_extension.isolation.doctrine_isolator'
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'behat_health_checker' }

  oro_behat_extension.health_checker.feature_cs_ckecker:
    class: Labudzinski\TestFrameworkBundle\Behat\HealthChecker\FeatureCSChecker
    tags:
      - { name: 'behat_health_checker' }

  oro_behat_extension.health_checker.result_printer_subscriber:
    class: Labudzinski\TestFrameworkBundle\Behat\HealthChecker\ResultPrinterSubscriber
    arguments:
      - '@cli.output'
    tags:
      - { name: 'health_checker_aware' }

  oro_behat_extension.health_checker.result_interpretation:
    class: Labudzinski\TestFrameworkBundle\Behat\HealthChecker\ResultInterpretation
    tags:
      - { name: 'health_checker_aware' }
