services:
  oro_behat_extension.isolation.test_isolation_subscriber:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\EventListener\TestIsolationSubscriber'
    arguments:
      - ~
    tags:
      - { name: 'event_dispatcher.subscriber', priority: 100 }

  oro_behat_extension.isolation.unix_file_cache_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\UnixFileCacheIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 100 }

  oro_behat_extension.isolation.windows_file_cache_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\WindowsFileCacheIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 100 }

  oro_behat_extension.isolation.windows_mysql_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\WindowsMysqlIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.unix_mysql_simple_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\UnixMysqlSyncIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.unix_pgsql_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\UnixPgsqlIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 110 }

  oro_behat_extension.isolation.kernel_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\KernelIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 120 }

  oro_behat_extension.isolation.dbal_message_queue_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\DbalMessageQueueIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 200 }

  oro_behat_extension.isolation.amqp_message_queue_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\AmqpMessageQueueIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 200 }

  oro_behat_extension.isolation.inital_massage_queue_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\InitalMessageQueueIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 50 }
      - { name: 'message_queue_isolator_aware' }

  oro_behat_extension.isolation.doctrine_isolator:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\DoctrineIsolator'
    arguments:
      - '@symfony2_extension.kernel'
      - '@oro_test.context.fixture_loader'
      - '@oro_test.alice_loader'
    tags:
      - { name: 'oro_behat.isolator', priority: 300 }

  oro_behat_extension.isolation.import_export:
    class: 'Labudzinski\TestFrameworkBundle\Behat\Isolation\ImportExportIsolator'
    arguments:
      - '@symfony2_extension.kernel'
    tags:
      - { name: 'oro_behat.isolator', priority: 100 }
