acls:
    test_action:
        label: test_action
        type: action

    test_entity_view:
        type: entity
        class: Labudzinski\TestFrameworkBundle\Entity\TestActivity
        permission: VIEW

    test_entity_delete:
        type: entity
        class: Labudzinski\TestFrameworkBundle\Entity\TestActivity
        permission: DELETE

